# Generated by Django 4.2.7 on 2023-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldetails',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
