# Generated by Django 4.2.7 on 2023-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_donordetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('mobilnumber', models.CharField(default='', max_length=100)),
                ('createpassword', models.CharField(default='', max_length=10)),
                ('confirmpassword', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
